### ISSUE TITLE
Platform error media_player.rn301 - Integration 'rn301' not found.

### ISSUE THREAD

**Issue by Sku1ly** [vrih/homeassistant-rn301#4]
Hi,
Thanks for this component, hopefully I can get it working with your help.

I've done as the readme instructs, copied raw file to custom_components\media_player\rn301.py but home assistant comes back with the error from the title.

Have I missed something or is it no longer supported?

Thanks

**Comment by vrih** [comment]
I ran into some trouble with paths previously. I moved the file to be in `custom_components/hifi_yamaha/` and then specify in configuration.yaml as

```
media_player:
  - platform: hifi_yamaha
    host: 192.168.1.11
```

If that works for you I'll update the readme

**Comment by Sku1ly** [comment]
Thanks for replying, I forgot about this issue and I found a fork in the mean time which worked for me.

https://github.com/yanoosh/homeassistant-rn301

Appreciate the work you've done in making this component.
